---
- name: "Install plugins"
  grafana_plugin:
    name: "{{ item }}"
    with_items:
      - vonage-status-panel
      - test
    version: latest
    state: presen
  notify:
    - restart grafana-server
  register: server_start_status

- name: "Check if Grafana console is accessible."
  import_tasks: check-grafana-console-access.yml
  when: server_start_status