---
- name: "Install Grafana server."
  yum:
    name: grafana
    enablerepo: grafana
    state: present
  become: yes

- name: "Start and enable Grafana server."
  service: name=grafana-server state=started enabled=yes
  become: yes
  register: server_start_status

- name: "Check if Grafana console is accessible."
  import_tasks: check-grafana-console-access.yml
  when: server_start_status