---
- name: "Install Grafana server"
  yum:
    name: grafana
    enablerepo: grafana
    state: present
  become: yes

- name: "Start and enable grafana-server"
  service: name=grafana-server state=started enabled=yes
  become: yes

- name: "Install plsuings"
  grafana_plugin:
    name: {{ item }}
    with_items:
      - vonage-status-panel
    version: latest
    state: presen

    service: name={{ item }} state=restarted
    #       with_items:
    #         - zabbix-server
    #         - zabbix-proxy